var gImgs = [
    {id: 1, url: `./img/1.jpg`, keywords: ['funny', 'trump']},
    {id: 2, url: `./img/2.jpg`, keywords: ['animal', 'cute']},
    {id: 3, url: `./img/3.jpg`, keywords: ['animal', 'cute']},
    {id: 4, url: `./img/4.jpg`, keywords: ['animal', 'cute']},
    {id: 5, url: `./img/5.jpg`, keywords: ['funny', 'kids']},
    {id: 6, url: `./img/6.jpg`, keywords: ['aliens', 'funny']},
    {id: 7, url: `./img/7.jpg`, keywords: ['kids', 'funny']},
    {id: 8, url: `./img/8.jpg`, keywords: ['smile']},
    {id: 9, url: `./img/9.jpg`, keywords: ['smile','kids', 'evil']},
    {id: 10, url: `./img/10.jpg`, keywords: ['smile','obama']},
    {id: 11, url: `./img/11.jpg`, keywords: ['awkward']},
    {id: 12, url: `./img/12.jpg`, keywords: ['funny', 'tv']},
    {id: 13, url: `./img/13.jpg`, keywords: ['leonardo', 'tv', 'smile','movie']},
    {id: 14, url: `./img/14.jpg`, keywords: ['glasses', 'matrix', 'movie','tv']},
    {id: 15, url: `./img/15.jpg`, keywords: ['one does not', 'lord of the rings', 'movie','tv', 'funny']},
    {id: 16, url: `./img/16.jpg`, keywords: ['star trak','movie','tv', 'funny']},
    {id: 17, url: `./img/17.jpg`, keywords: ['putin','scary']},
    {id: 18, url: `./img/18.jpg`, keywords: ['toy story','movie', 'tv', 'funny', 'smile']},
    {id: 19, url: `./img/19.jpg`, keywords: ['movie', 'tv', 'funny']},
    {id: 20, url: `./img/20.jpg`, keywords: ['animal','funny']},
    {id: 21, url: `./img/21.jpg`, keywords: ['happy','funny', 'smile']},
    {id: 22, url: `./img/22.jpg`, keywords: ['trump','funny']},
    {id: 23, url: `./img/23.jpg`, keywords: ['animal','funny']},
    {id: 24, url: `./img/24.jpg`, keywords: ['oprah','tv', 'you', 'get']},
    {id: 25, url: `./img/25.jpg`, keywords: ['happy','funny', 'look', 'at', 'all']}
]